name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install tests dependences
        run: |
          cd Tests
          npm install

      - name: Go to latest folder and install the needed dependences
        run: |
          cd Website
          NEWEST_DIR="$(ls -td -- */ | head -n1)"
          echo "The newest directory is: $NEWEST_DIR"
          cd "$NEWEST_DIR"
          npm install

          PORT=3005 npm run dev &
          
          echo "BASE_URL=http://localhost:3005" >> tests/.env
          sleep 10

      - name: Run Tests
        run: |
          cd tests
          npx playwright test
