name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Start server
        run: |
          # 1) We define a fixed port, e.g. 3005
          PORT=3005 npm run dev &

          # 2) Append the environment variable to your test .env
          echo "BASE_URL=http://localhost:3005" >> tests/.env

          # 3) Give the server time to start
          sleep 5

      - name: Install test dependencies
        run: |
          cd tests
          npm install

      - name: Run Tests
        run: |
          cd tests
          npx playwright test
