name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Go to latest folder and install the needed dependences
        run: |
          cd Website
          NEWEST_DIR="$(ls -td -- */ | head -n1)"
          echo "The newest directory is: $NEWEST_DIR"
          cd "$NEWEST_DIR"
          npm install

      - name: Install the tests dependences
        run: |
          cd Tests
          npm install

      - name: Start server
        run: |
          # 1) We define a fixed port, e.g. 3005
          PORT=3005 npm run dev &

          # 2) Append the environment variable to your test .env
          echo "BASE_URL=http://localhost:3005" >> tests/.env

          # 3) Give the server time to start
          sleep 5

      - name: Run Tests
        run: |
          cd tests
          npx playwright test
