name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install tests dependences
        run: |
          cd Tests
          npm install
          npx playwright install --with-deps

      - name: Go to latest folder and install the needed dependences
        run: |
          cd Website
          NEWEST_DIR="$(ls -td -- */ | head -n1)"
          echo "The newest directory is: $NEWEST_DIR"
          cd "$NEWEST_DIR"
          npm install

          PORT=3005 npm run dev &

      - name: Add the port to the .env file
        run: |
          cd Tests
          echo "BASE_URL=http://localhost:3005/" > .env

      - name: Run Tests
        run: |
          cd Tests
          npx playwright test
